/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpdsibo.Interfaces;

import com.complexible.common.rdf.model.Values;
import com.complexible.stardog.StardogException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.openrdf.query.QueryEvaluationException;
import tpdsibo.Control.StardogControl;
import tpdsibo.Entidades.Persona;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import tpdsibo.Entidades.Puesto;

/**
 *
 * @author Usuario
 */
public class PantallaRecomendar extends javax.swing.JFrame {
    
   List<Persona> postulantes = null;

    /**
     * Creates new form PantallaRecomendar2
     */
    public PantallaRecomendar() {
       initComponents();    
       try {

           //Inicialmente se muestran todos los postulantes en la tabla
           postulantes = StardogControl.getInstancia().
                   consultarPosiblesPostulantes(Values.iri("http://www.frsf.utn.edu.ar/DSIBO-2015/Sistema-Recomendador-Recursos-Humanos#Postulante"));
           poblarTablaPostulantes(postulantes);
           
           poblarComboPuestos();
           
           
           actualizarAntecedentes(new ArrayList<String>()); //???
           
           

           
       } catch (StardogException ex) {
           Logger.getLogger(PantallaRecomendar.class.getName()).log(Level.SEVERE, null, ex);
       } catch (QueryEvaluationException ex) {
           Logger.getLogger(PantallaRecomendar.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPuesto = new javax.swing.JLabel();
        cmbPuestos = new javax.swing.JComboBox<>();
        btnRecomendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPostulantes = new javax.swing.JTable();
        lblAntecedentes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(181, 221, 181));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Recomendador de Recursos Humanos ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(208, 208, 208))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Búsqueda de candidatos");

        lblPuesto.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblPuesto.setText("Puesto: ");

        cmbPuestos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        cmbPuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPuestosActionPerformed(evt);
            }
        });

        btnRecomendar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnRecomendar.setText("Ver postulantes recomendados");
        btnRecomendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecomendarMouseClicked(evt);
            }
        });
        btnRecomendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomendarActionPerformed(evt);
            }
        });

        tblPostulantes.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tblPostulantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPostulantes);

        lblAntecedentes.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        lblAntecedentes.setText("Antecedentes laborales");

        jList1.setBackground(new java.awt.Color(224, 224, 255));
        jList1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPuesto)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRecomendar))
                            .addComponent(jScrollPane1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(lblAntecedentes)
                                .addGap(90, 90, 90)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuesto)
                    .addComponent(cmbPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecomendar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAntecedentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecomendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecomendarMouseClicked
        Puesto puestoSeleccionado  = (Puesto) cmbPuestos.getSelectedItem();
        
        try {

           
           postulantes = StardogControl.getInstancia().consultarPosiblesPostulantes(puestoSeleccionado.getPostulante());
           
           
       } catch (Exception ex) {
           Logger.getLogger(PantallaRecomendar.class.getName()).log(Level.SEVERE, null, ex);
       }
        

        tblPostulantes.clearSelection();
        tblPostulantes.removeAll();
        poblarTablaPostulantes(postulantes);
        
    }//GEN-LAST:event_btnRecomendarMouseClicked

    private void cmbPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPuestosActionPerformed

    private void btnRecomendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecomendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRecomendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRecomendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRecomendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRecomendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRecomendar().setVisible(true); 
            }
        });
    }
    
    public void poblarComboPuestos(){
        try{
            List<Puesto> puestos = StardogControl.getInstancia().obtenerPuestosParaCombo();
            
            DefaultComboBoxModel comboModel = new DefaultComboBoxModel(puestos.toArray());
            cmbPuestos.setModel(comboModel);
            

        }
        catch(Exception e){//Error
            System.out.print(e);
        }
    }
    

    public void poblarTablaPostulantes(List<Persona> postulantes){
        String[] columnas = {"URI", "Edad", "Sexo", "Desempeño","Liderazgo","Habilitado"};
        TablaPostulantesTableModel tblModel = new TablaPostulantesTableModel(postulantes, columnas);
        
 
        tblPostulantes.setModel(tblModel); //Se agrega el tblModel a la tabla
        
        
        
        tblPostulantes.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            TablaPostulantesTableModel m = (TablaPostulantesTableModel) tblPostulantes.getModel();
            Persona postulanteSeleccionado = m.getPostulantePorFila(tblPostulantes.getSelectedRow());
            poblarAntecedentes(postulanteSeleccionado);
        }
    });
            
            
        }
    
    public void poblarAntecedentes(Persona p){
        List<String> antecedentes = new ArrayList<String>();
        if(p != null){
            

            for (Puesto puesto : p.getAntecedentes()){
                antecedentes.add(puesto.getNombre());
            }
        }
        
        actualizarAntecedentes(antecedentes);
        
    }
    
    private void actualizarAntecedentes(List<String> l) {
        DefaultListModel listModel = new DefaultListModel();
        
        for (String s : l)
            listModel.addElement(s);
        
        jList1.setModel(listModel);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecomendar;
    private javax.swing.JComboBox<String> cmbPuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAntecedentes;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JTable tblPostulantes;
    // End of variables declaration//GEN-END:variables


}
