/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpdsibo.Interfaces;

import com.complexible.common.rdf.model.Values;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import tpdsibo.Control.StardogControl;
import tpdsibo.Entidades.Persona;
import tpdsibo.Entidades.Puesto;

/**
 *
 * @author Usuario
 */
public class PantallaAltaPostulantes extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAltaPostulantes
     */
    
    Persona nuevaPersona = new Persona();
    List<Puesto> antecedentes = new ArrayList<Puesto>();
    
    public PantallaAltaPostulantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSexo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblHabilitado = new javax.swing.JLabel();
        lblDesempeño = new javax.swing.JLabel();
        lblLiderazgo = new javax.swing.JLabel();
        rdbHabilitadoSi = new javax.swing.JRadioButton();
        rdbHabilitadoNo = new javax.swing.JRadioButton();
        rdbLiderazgoNo = new javax.swing.JRadioButton();
        rdbLiderazgoSi = new javax.swing.JRadioButton();
        cmbDesempeño = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chkSubdirectorB = new javax.swing.JCheckBox();
        chkEmpleadoDesarrolloSinExp = new javax.swing.JCheckBox();
        chkEmpleadoMantenimientoConExp = new javax.swing.JCheckBox();
        chkEmpleadoServicioSinExp = new javax.swing.JCheckBox();
        chkDirectorB = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        chkEmpleadoServicioConExp = new javax.swing.JCheckBox();
        chkDirectorA = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkSubdirectorA = new javax.swing.JCheckBox();
        chkEmpleadoMantenimientoSinExp = new javax.swing.JCheckBox();
        chkEmpleadoDesarrolloConExp = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        chkSubJefaServicio = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chkJefeMantenimiento = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        chkJefaServicio = new javax.swing.JCheckBox();
        lblAntecedentes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Inscripción Postulantes");

        lblSexo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblSexo.setText("Sexo:");

        lblNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblEdad.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblEdad.setText("Edad:");

        cmbSexo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        cmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        lblHabilitado.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblHabilitado.setText("Habilitado:");

        lblDesempeño.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblDesempeño.setText("Desempeño:");

        lblLiderazgo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblLiderazgo.setText("Liderazgo:");

        rdbHabilitadoSi.setBackground(new java.awt.Color(255, 255, 255));
        rdbHabilitadoSi.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rdbHabilitadoSi.setText("Si");
        rdbHabilitadoSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbHabilitadoSiStateChanged(evt);
            }
        });

        rdbHabilitadoNo.setBackground(new java.awt.Color(255, 255, 255));
        rdbHabilitadoNo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rdbHabilitadoNo.setText("No");
        rdbHabilitadoNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbHabilitadoNoStateChanged(evt);
            }
        });
        rdbHabilitadoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHabilitadoNoActionPerformed(evt);
            }
        });

        rdbLiderazgoNo.setBackground(new java.awt.Color(255, 255, 255));
        rdbLiderazgoNo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rdbLiderazgoNo.setText("No");
        rdbLiderazgoNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbLiderazgoNoStateChanged(evt);
            }
        });

        rdbLiderazgoSi.setBackground(new java.awt.Color(255, 255, 255));
        rdbLiderazgoSi.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rdbLiderazgoSi.setText("Si");
        rdbLiderazgoSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbLiderazgoSiStateChanged(evt);
            }
        });
        rdbLiderazgoSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLiderazgoSiActionPerformed(evt);
            }
        });

        cmbDesempeño.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        cmbDesempeño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No posee", "Regular", "Bueno", "Muy Bueno" }));

        jPanel2.setBackground(new java.awt.Color(181, 221, 181));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Recomendador de Recursos Humanos ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));

        chkSubdirectorB.setBackground(new java.awt.Color(237, 237, 237));
        chkSubdirectorB.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkSubdirectorB.setText("Subdirector Proyecto \"B\"");
        chkSubdirectorB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSubdirectorBStateChanged(evt);
            }
        });

        chkEmpleadoDesarrolloSinExp.setBackground(new java.awt.Color(237, 237, 237));
        chkEmpleadoDesarrolloSinExp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkEmpleadoDesarrolloSinExp.setText("Empleado de Desarrollo (Sin exp.)");
        chkEmpleadoDesarrolloSinExp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEmpleadoDesarrolloSinExpStateChanged(evt);
            }
        });

        chkEmpleadoMantenimientoConExp.setBackground(new java.awt.Color(237, 237, 237));
        chkEmpleadoMantenimientoConExp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkEmpleadoMantenimientoConExp.setText("Empleado de Mantenimiento (Con exp.)");
        chkEmpleadoMantenimientoConExp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEmpleadoMantenimientoConExpStateChanged(evt);
            }
        });

        chkEmpleadoServicioSinExp.setBackground(new java.awt.Color(237, 237, 237));
        chkEmpleadoServicioSinExp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkEmpleadoServicioSinExp.setText("Empleado de Servicio (Sin exp.)");
        chkEmpleadoServicioSinExp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEmpleadoServicioSinExpStateChanged(evt);
            }
        });

        chkDirectorB.setBackground(new java.awt.Color(237, 237, 237));
        chkDirectorB.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkDirectorB.setText("Director Proyecto \"B\"");
        chkDirectorB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkDirectorBStateChanged(evt);
            }
        });
        chkDirectorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDirectorBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 2, 10)); // NOI18N
        jLabel2.setText("(Seleccionar cada puesto ocupado por el postulante hasta el momento)");

        jButton2.setBackground(new java.awt.Color(181, 221, 181));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chkEmpleadoServicioConExp.setBackground(new java.awt.Color(237, 237, 237));
        chkEmpleadoServicioConExp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkEmpleadoServicioConExp.setText("Empleado de Servicio (Con exp.)");
        chkEmpleadoServicioConExp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEmpleadoServicioConExpStateChanged(evt);
            }
        });

        chkDirectorA.setBackground(new java.awt.Color(237, 237, 237));
        chkDirectorA.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkDirectorA.setText("Director Proyecto \"A\"");
        chkDirectorA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkDirectorAStateChanged(evt);
            }
        });
        chkDirectorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDirectorAActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Área Servicio");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Área Desarrollo");

        chkSubdirectorA.setBackground(new java.awt.Color(237, 237, 237));
        chkSubdirectorA.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkSubdirectorA.setText("Subdirector Proyecto \"A\"");
        chkSubdirectorA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSubdirectorAStateChanged(evt);
            }
        });

        chkEmpleadoMantenimientoSinExp.setBackground(new java.awt.Color(237, 237, 237));
        chkEmpleadoMantenimientoSinExp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkEmpleadoMantenimientoSinExp.setText("Empleado de Mantenimiento (Sin exp.)");
        chkEmpleadoMantenimientoSinExp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEmpleadoMantenimientoSinExpStateChanged(evt);
            }
        });

        chkEmpleadoDesarrolloConExp.setBackground(new java.awt.Color(237, 237, 237));
        chkEmpleadoDesarrolloConExp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkEmpleadoDesarrolloConExp.setText("Empleado de Desarrollo (Con exp.)");
        chkEmpleadoDesarrolloConExp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEmpleadoDesarrolloConExpStateChanged(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(181, 221, 181));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkSubJefaServicio.setBackground(new java.awt.Color(237, 237, 237));
        chkSubJefaServicio.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkSubJefaServicio.setText("Subjefa de Servicio");
        chkSubJefaServicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSubJefaServicioStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Directivos");

        chkJefeMantenimiento.setBackground(new java.awt.Color(237, 237, 237));
        chkJefeMantenimiento.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkJefeMantenimiento.setText("Jefe de Mantenimiento");
        chkJefeMantenimiento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkJefeMantenimientoStateChanged(evt);
            }
        });
        chkJefeMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJefeMantenimientoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Área Mantenimiento");

        chkJefaServicio.setBackground(new java.awt.Color(237, 237, 237));
        chkJefaServicio.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chkJefaServicio.setText("Jefa de Servicio");
        chkJefaServicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkJefaServicioStateChanged(evt);
            }
        });

        lblAntecedentes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblAntecedentes.setForeground(new java.awt.Color(17, 17, 17));
        lblAntecedentes.setText("Antecedentes Laborales");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDirectorB)
                    .addComponent(chkSubdirectorB)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(chkSubdirectorA)
                            .addComponent(chkDirectorA))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSubJefaServicio)
                                    .addComponent(chkJefaServicio)
                                    .addComponent(chkEmpleadoServicioConExp)
                                    .addComponent(chkEmpleadoServicioSinExp))))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkEmpleadoMantenimientoConExp)
                                    .addComponent(chkJefeMantenimiento)
                                    .addComponent(chkEmpleadoMantenimientoSinExp))))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkEmpleadoDesarrolloConExp)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jButton2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(chkEmpleadoDesarrolloSinExp))))))
                    .addComponent(lblAntecedentes)
                    .addComponent(jLabel2))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkDirectorA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSubdirectorA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDirectorB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSubdirectorB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkJefaServicio)
                            .addComponent(chkJefeMantenimiento)
                            .addComponent(chkEmpleadoDesarrolloConExp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkEmpleadoMantenimientoConExp)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkSubJefaServicio)
                                .addComponent(chkEmpleadoDesarrolloSinExp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEmpleadoServicioConExp)
                            .addComponent(chkEmpleadoMantenimientoSinExp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkEmpleadoServicioSinExp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        lblAntecedentes.getAccessibleContext().setAccessibleName("lblAntecedentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSexo)
                                .addGap(37, 37, 37)
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombre))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEdad)
                                    .addGap(35, 35, 35)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHabilitado)
                            .addComponent(lblLiderazgo)
                            .addComponent(lblDesempeño))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbLiderazgoSi)
                                    .addComponent(rdbHabilitadoSi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbLiderazgoNo)
                                    .addComponent(rdbHabilitadoNo)))
                            .addComponent(cmbDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHabilitado)
                    .addComponent(rdbHabilitadoSi)
                    .addComponent(rdbHabilitadoNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLiderazgo)
                    .addComponent(rdbLiderazgoSi)
                    .addComponent(rdbLiderazgoNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad)
                    .addComponent(lblDesempeño)
                    .addComponent(cmbDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        lblSexo.getAccessibleContext().setAccessibleName("lblSexo");
        lblNombre.getAccessibleContext().setAccessibleName("lblNombre");
        lblEdad.getAccessibleContext().setAccessibleName("lblEdad");
        lblHabilitado.getAccessibleContext().setAccessibleName("lblHabilitado");
        lblDesempeño.getAccessibleContext().setAccessibleName("lblDesempeño");
        lblLiderazgo.getAccessibleContext().setAccessibleName("lblLiderazgo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkJefeMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJefeMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJefeMantenimientoActionPerformed

    private void rdbLiderazgoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLiderazgoSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbLiderazgoSiActionPerformed

    private void chkDirectorAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkDirectorAStateChanged
  
        setearPuesto("DirectorProyectoA", chkDirectorA);

    }//GEN-LAST:event_chkDirectorAStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(txtNombre.getText().isEmpty() || txtEdad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Hay campos vacíos");
        
        }
        nuevaPersona.setNombre(txtNombre.getText().toString());
        nuevaPersona.setSexo(cmbSexo.getSelectedItem().toString());
        nuevaPersona.setEdad(Integer.parseInt(txtEdad.getText()));
        nuevaPersona.setDesempeño(cmbDesempeño.getSelectedItem().toString());
        
        //GUARDAR
        StardogControl.getInstancia().guardar(nuevaPersona);
        
        JOptionPane.showMessageDialog(this, "Postulante inscripto con éxito");
        limpiarPantalla();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkDirectorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDirectorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDirectorAActionPerformed

    private void chkDirectorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDirectorBActionPerformed


    }//GEN-LAST:event_chkDirectorBActionPerformed

    private void chkDirectorBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkDirectorBStateChanged

        setearPuesto("DirectorProyectoB", chkDirectorB);
    }//GEN-LAST:event_chkDirectorBStateChanged

    private void chkJefeMantenimientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkJefeMantenimientoStateChanged

        setearPuesto("JefeMantenimiento", chkJefeMantenimiento);
    }//GEN-LAST:event_chkJefeMantenimientoStateChanged

    private void chkSubdirectorAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSubdirectorAStateChanged

        setearPuesto("SubDirectorProyectoA", chkSubdirectorA);
    }//GEN-LAST:event_chkSubdirectorAStateChanged

    private void chkSubdirectorBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSubdirectorBStateChanged

        setearPuesto("SubDirectorProyectoB", chkSubdirectorB);
    }//GEN-LAST:event_chkSubdirectorBStateChanged

    private void chkJefaServicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkJefaServicioStateChanged

      setearPuesto("JefaServicio", chkJefaServicio);
    }//GEN-LAST:event_chkJefaServicioStateChanged

    private void chkSubJefaServicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSubJefaServicioStateChanged

        setearPuesto("SubJefaServicio", chkSubJefaServicio);
    }//GEN-LAST:event_chkSubJefaServicioStateChanged

    private void chkEmpleadoDesarrolloSinExpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEmpleadoDesarrolloSinExpStateChanged
        
        setearPuesto("EmpleadoDesarrolloSinExp", chkEmpleadoDesarrolloSinExp);
    }//GEN-LAST:event_chkEmpleadoDesarrolloSinExpStateChanged

    private void chkEmpleadoDesarrolloConExpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEmpleadoDesarrolloConExpStateChanged

        setearPuesto("EmpleadoDesarrolloConExp", chkEmpleadoDesarrolloConExp);
    }//GEN-LAST:event_chkEmpleadoDesarrolloConExpStateChanged

    private void chkEmpleadoServicioConExpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEmpleadoServicioConExpStateChanged

        setearPuesto("EmpleadoServicioConExp", chkEmpleadoServicioConExp);
    }//GEN-LAST:event_chkEmpleadoServicioConExpStateChanged

    private void chkEmpleadoServicioSinExpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEmpleadoServicioSinExpStateChanged

        setearPuesto("EmpleadoServicioSinExp", chkEmpleadoServicioSinExp);
    }//GEN-LAST:event_chkEmpleadoServicioSinExpStateChanged

    private void chkEmpleadoMantenimientoConExpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEmpleadoMantenimientoConExpStateChanged

        setearPuesto("EmpleadoMantenimientoConExp", chkEmpleadoMantenimientoConExp);
    }//GEN-LAST:event_chkEmpleadoMantenimientoConExpStateChanged

    private void chkEmpleadoMantenimientoSinExpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEmpleadoMantenimientoSinExpStateChanged

        setearPuesto("EmpleadoMantenimientoSinExp", chkEmpleadoMantenimientoSinExp);
    }//GEN-LAST:event_chkEmpleadoMantenimientoSinExpStateChanged

    private void rdbHabilitadoSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbHabilitadoSiStateChanged
        
        if(rdbHabilitadoSi.isSelected())
            nuevaPersona.setHabilitado(true);
        else
            nuevaPersona.setHabilitado(false);
    }//GEN-LAST:event_rdbHabilitadoSiStateChanged

    private void rdbHabilitadoNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbHabilitadoNoStateChanged
        
        if(rdbHabilitadoNo.isSelected())
            nuevaPersona.setHabilitado(false);
        else
            nuevaPersona.setHabilitado(true);
    }//GEN-LAST:event_rdbHabilitadoNoStateChanged

    private void rdbLiderazgoSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbLiderazgoSiStateChanged
        
        if(rdbLiderazgoSi.isSelected())
            nuevaPersona.setLiderazgo(true);
        else
            nuevaPersona.setLiderazgo(false);
    }//GEN-LAST:event_rdbLiderazgoSiStateChanged

    private void rdbLiderazgoNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbLiderazgoNoStateChanged
        
        if(rdbLiderazgoNo.isSelected())
            nuevaPersona.setLiderazgo(false);
        else
            nuevaPersona.setLiderazgo(true);
    }//GEN-LAST:event_rdbLiderazgoNoStateChanged

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoActionPerformed

    private void rdbHabilitadoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHabilitadoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbHabilitadoNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int aux = JOptionPane.showConfirmDialog(this, "Desea salir?");
        if (JOptionPane.OK_OPTION == aux) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAltaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAltaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAltaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAltaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAltaPostulantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkDirectorA;
    private javax.swing.JCheckBox chkDirectorB;
    private javax.swing.JCheckBox chkEmpleadoDesarrolloConExp;
    private javax.swing.JCheckBox chkEmpleadoDesarrolloSinExp;
    private javax.swing.JCheckBox chkEmpleadoMantenimientoConExp;
    private javax.swing.JCheckBox chkEmpleadoMantenimientoSinExp;
    private javax.swing.JCheckBox chkEmpleadoServicioConExp;
    private javax.swing.JCheckBox chkEmpleadoServicioSinExp;
    private javax.swing.JCheckBox chkJefaServicio;
    private javax.swing.JCheckBox chkJefeMantenimiento;
    private javax.swing.JCheckBox chkSubJefaServicio;
    private javax.swing.JCheckBox chkSubdirectorA;
    private javax.swing.JCheckBox chkSubdirectorB;
    private javax.swing.JComboBox<String> cmbDesempeño;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAntecedentes;
    private javax.swing.JLabel lblDesempeño;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblHabilitado;
    private javax.swing.JLabel lblLiderazgo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rdbHabilitadoNo;
    private javax.swing.JRadioButton rdbHabilitadoSi;
    private javax.swing.JRadioButton rdbLiderazgoNo;
    private javax.swing.JRadioButton rdbLiderazgoSi;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    
    private void setearPuesto(String nombrePuesto, JCheckBox checkPuesto){
        
        Puesto puesto = new Puesto();
        nuevaPersona.setAntecedentes(antecedentes);
        
        puesto.setIriPuesto(Values.iri("http://www.frsf.utn.edu.ar/DSIBO-2015/Sistema-Recomendador-Recursos-Humanos#" + nombrePuesto));
        
        if(checkPuesto.isSelected()==true){
            nuevaPersona.getAntecedentes().add(puesto);
        }
        else{
            if(nuevaPersona.getAntecedentes().contains(puesto))
               nuevaPersona.getAntecedentes().remove(puesto);
            
           /*List<Puesto> antecedentes = nuevaPersona.getAntecedentes();
            
            for(Puesto p : antecedentes){
                if(p.getUriPuesto().equals(Values.uri("http://www.frsf.utn.edu.ar/DSIBO-2015/Sistema-Recomendador-Recursos-Humanos#" + nombrePuesto)))
                    antecedentes.remove(p);
            }*/
        }
    }

    private void limpiarPantalla() {
      
        txtNombre.setText("");
        txtEdad.setText("");
        cmbDesempeño.setSelectedIndex(0);
        chkDirectorA.setSelected(false);
        chkDirectorB.setSelected(false);
        chkSubdirectorA.setSelected(false);
        chkSubdirectorB.setSelected(false);
        chkJefaServicio.setSelected(false);
        chkSubJefaServicio.setSelected(false);
        chkEmpleadoServicioConExp.setSelected(false);
        chkEmpleadoServicioSinExp.setSelected(false);
        chkEmpleadoDesarrolloConExp.setSelected(false);
        chkEmpleadoDesarrolloSinExp.setSelected(false);
        chkEmpleadoMantenimientoConExp.setSelected(false);
        chkEmpleadoMantenimientoSinExp.setSelected(false);
        chkJefeMantenimiento.setSelected(false);
        antecedentes = new ArrayList<Puesto>();
        nuevaPersona = new Persona();
        
    }
    
}
